# Generated by Django 6.0 on 2025-12-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "Cook", "verbose_name_plural": "Cooks"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_manage_dishes", "Can create, update and delete dishes")
                ],
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
    ]
